const nodemailer = require('nodemailer');

const generateProgressBar = (value, min, max, emoji) => {
  const percentage = Math.max(0, Math.min(100, ((value - min) / (max - min)) * 100));
  const filledBlocks = Math.round((percentage / 100) * 10);
  const emptyBlocks = 10 - filledBlocks;
  
  // Use colored squares for email
  let color = '#4CAF50'; // Green
  if (percentage < 20 || percentage > 80) color = '#f44336'; // Red
  else if (percentage < 40 || percentage > 60) color = '#FFC107'; // Yellow

  let barHtml = `<div style="display: flex; align-items: center; gap: 10px; margin: 10px 0;">
    <div style="width: 30px; font-size: 24px;">${emoji}</div>
    <div style="flex-grow: 1; background: #e0e0e0; border-radius: 10px; height: 12px; overflow: hidden;">
      <div style="width: ${percentage}%; background: ${color}; height: 100%; border-radius: 10px;"></div>
    </div>
    <div style="width: 60px; text-align: right; font-weight: bold;">${value}</div>
  </div>`;
  return barHtml;
};

const sendAlertEmail = async (subject, aiText, sensorData) => {
  if (!process.env.GMAIL_USER || !process.env.GMAIL_APP_PASSWORD || !process.env.ALERT_EMAIL_RECIPIENT) {
    console.log("Email credentials not fully configured. Skipping email alert.");
    return;
  }

  // Parse AI Markdown to basic HTML (bold text)
  let formattedText = aiText.replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>');
  formattedText = formattedText.replace(/\n/g, '<br>');

  const htmlContent = `
    <div style="font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; max-width: 600px; margin: auto; border: 1px solid #ddd; border-radius: 12px; overflow: hidden; box-shadow: 0 4px 15px rgba(0,0,0,0.1);">
      <div style="background: linear-gradient(135deg, #2E7D32, #4CAF50); color: white; padding: 20px; text-align: center;">
        <h1 style="margin: 0; font-size: 24px;">🌿 GreenPulse Alert</h1>
        <p style="margin: 5px 0 0 0; opacity: 0.9;">Smart Indoor Plant-Care System</p>
      </div>
      
      <div style="padding: 25px; background: #ffffff; color: #333;">
        <div style="background: #FFF3E0; border-left: 4px solid #FF9800; padding: 15px; border-radius: 0 8px 8px 0; margin-bottom: 25px;">
          ${formattedText}
        </div>

        <h3 style="color: #2E7D32; border-bottom: 2px solid #E8F5E9; padding-bottom: 8px;">📊 Current Sensor Readings</h3>
        
        <div style="background: #F5F5F5; padding: 15px; border-radius: 8px;">
          ${generateProgressBar(sensorData.soilMoisture, 0, 100, '💧')}
          <div style="font-size: 12px; color: #666; margin-left: 40px; margin-top: -5px; margin-bottom: 10px;">Soil Moisture (%)</div>
          
          ${generateProgressBar(sensorData.temperature, 0, 50, '🌡️')}
          <div style="font-size: 12px; color: #666; margin-left: 40px; margin-top: -5px; margin-bottom: 10px;">Temperature (°C)</div>
          
          ${generateProgressBar(sensorData.humidity, 0, 100, '☁️')}
          <div style="font-size: 12px; color: #666; margin-left: 40px; margin-top: -5px; margin-bottom: 10px;">Humidity (%)</div>
          
          ${generateProgressBar(sensorData.light, 0, 1000, '☀️')}
          <div style="font-size: 12px; color: #666; margin-left: 40px; margin-top: -5px; margin-bottom: 10px;">Light Level (Lux)</div>
        </div>
      </div>
      
      <div style="background: #f9f9f9; padding: 15px; text-align: center; font-size: 12px; color: #888; border-top: 1px solid #ddd;">
        Generated by GreenPulse AI Engine &bull; ${new Date().toLocaleString()}
      </div>
    </div>
  `;

  try {
    const transporter = nodemailer.createTransport({
      service: 'gmail',
      auth: {
        user: process.env.GMAIL_USER,
        pass: process.env.GMAIL_APP_PASSWORD
      }
    });

    const mailOptions = {
      from: process.env.GMAIL_USER,
      to: process.env.ALERT_EMAIL_RECIPIENT,
      subject: subject,
      html: htmlContent
    };

    const info = await transporter.sendMail(mailOptions);
    console.log('Alert email sent: ' + info.response);
  } catch (error) {
    console.error('Error sending email:', error);
  }
};

module.exports = { sendAlertEmail };
